::@echo off

:: arguments can be version, debug/release (release being the default) and optionally x64 (default being "Any CPU")

set appName=LoggerMonitor
set "arch=x86"
if "%~1"=="x64" set "arch=x64\"
if "%~2"=="x64" set "arch=x64\"

set "config=Release"
if "%~1"=="debug" set "config=debug"
if "%~2"=="debug" set "config=debug"
if "%~1"=="Debug" set "config=debug"
if "%~2"=="Debug" set "config=debug"
if "%~1"=="product" set "config=product"
if "%~2"=="product" set "config=product"
if "%~1"=="Product" set "config=product"
if "%~2"=="Product" set "config=product"

:: go to the installer build folders
cd \Projektit\LoggerMonitor\LoggerMonitor\Installer

:: Compile - define the variables used in the harvested .wxs files. List all the .wxs files generated by the harvester and Analyzer.wxs file.
call "C:\Program Files (x86)\WiX Toolset v3.11\bin\Candle.exe" ^
-dLoggerMonitorProjectRootDir="\Projektit\LoggerMonitor\LoggerMonitor" ^
-dLoggerMonitorApp=%appName% ^
-dConfiguration=%config% ^
-dBinDir=..\bin\%config%\ ^
-arch %arch% ^
-v ^
-ext "c:\Program Files (x86)\WiX Toolset v3.11\bin\WixUtilExtension.dll" ^
%appName%.wxs || EXIT /B 1

:: Link - generate the Windows msi installer package. List all the .wixobj files generated by the compiler.
call "C:\Program Files (x86)\WiX Toolset v3.11\bin\Light.exe" -out %appName%.msi ^
-ext "c:\Program Files (x86)\WiX Toolset v3.11\bin\WixUtilExtension.dll" ^
LoggerMonitor.wixobj || EXIT /B 1

